use clap::{App, Arg, ArgMatches};
pub fn create_arg_parser() -> ArgMatches<'static> {
    App::new("VST-Bundler")
        .version("0.1.0")
        .author("Alex Z. <alexander.zywicki@gmail.com>")
        .about("Bundles VST Plugins")
        .arg(Arg::with_name("name")
                 .short("n")
                 .long("name")
                 .value_name("NAME")
                 .help("The name of the VST Plugin")
                 .required(true)
                 .takes_value(true))
        .arg(Arg::with_name("libpath")
                 .short("l")
                 .long("libpath")
                 .value_name("LIBPATH")
                 .help("The path to the plugin dylib")
                 .required(true))
        .arg(Arg::with_name("installdir")
                 .short("i")
                 .long("installdir")
                 .value_name("INSTALLDIR")
                 .required(false)
                 .help("The location to install the bundle to"))
        .arg(Arg::with_name("resource")
                 .short("r")
                 .long("resource")
                 .value_name("RESOURCE")
                 .required(false)
                 .help("Path to a resource file or directory"))
        .get_matches()
}
